Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [8]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


numpy. string_ is the NumPy datatype used for arrays containing fixed-width byte strings. On the other hand, str is a native Python type and can not be used as a datatype for NumPy arrays

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [10]:
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
for i in list_:
    print("Data Type of {} is".format(i),type(i))
for j in array_list:
    print("Data type of element {} of array_list is".format(j),type(j))

Data Type of 1 is <class 'str'>
Data Type of 2 is <class 'str'>
Data Type of 3 is <class 'str'>
Data Type of 4 is <class 'str'>
Data Type of 5 is <class 'str'>
Data type of element 1 of array_list is <class 'numpy.str_'>
Data type of element 2 of array_list is <class 'numpy.str_'>
Data type of element 3 of array_list is <class 'numpy.str_'>
Data type of element 4 of array_list is <class 'numpy.str_'>
Data type of element 5 of array_list is <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

-> Yes there are changes as new array_list now has all elements as int datatype while that of list_ is is still str

In [13]:
array_list = np.array(object = list_, dtype = int)
for i in array_list:
    print(type(i))
for j in list_:
    print("Data Type of {} is".format(j),type(j))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
Data Type of 1 is <class 'str'>
Data Type of 2 is <class 'str'>
Data Type of 3 is <class 'str'>
Data Type of 4 is <class 'str'>
Data Type of 5 is <class 'str'>


Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print("Shape of num_array is",np.shape(num_array))
print("Size of num_array is",np.size(num_array))

Shape of num_array is (2, 3)
Size of num_array is 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [13]:
x = np.zeros((3,3))
print("Array of 3*3 matrix is \n",x)

Array of 3*3 matrix is 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [16]:
identity_matrix = np.eye(5,5)
print("Identity matrix of 5*5 is \n",identity_matrix)

Identity matrix of 5*5 is 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
